// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PrepareImportMetadata(arg1, arg2) {
  return window['go']['main']['App']['PrepareImportMetadata'](arg1, arg2);
}

export function SaveImport(arg1) {
  return window['go']['main']['App']['SaveImport'](arg1);
}

export function SelectExecutable() {
  return window['go']['main']['App']['SelectExecutable']();
}

export function StartImport(arg1) {
  return window['go']['main']['App']['StartImport'](arg1);
}
