// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {metadata} from '../models';
import {model} from '../models';

export function PrepareImportMetadata(arg1:service.ImportDraft,arg2:Array<metadata.Source>):Promise<service.ImportMetadataResult>;

export function SaveImport(arg1:service.SaveImportRequest):Promise<model.Game>;

export function SelectExecutable():Promise<string>;

export function StartImport(arg1:string):Promise<service.StartImportResult>;
